---
- name: Create users with loop
  hosts: host0.lab.drv.internal
  tasks:
    - name: User creation task
      ansible.builtin.user:
        name: "{{ item['name'] }}"
        state: present
        groups: "{{ item['groups'] }}"
      loop:
        - name: mayer
          groups: wheel
        - name: mueller
          groups: root
