---
- name: Rollback operation lab-5
  hosts: host0.lab.drv.internal
  tasks:
    - name: Rollback user creation task
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
      loop:
        - mayer
        - mueller
