---
- name: fetch a file
  hosts: host0.lab.drv.internal
  become: false
  tasks:
    - name: stat file and copy to timestamp
      block:
        - name: stat file
          ansible.builtin.stat:
            path: /home/user/inventory
          register: result
          failed_when: result['stat']['exists']
      rescue:
        - name: copy file with timestamp
          ansible.builtin.command:
            cmd: cp /home/user/inventory /home/user/inventory-{{ ansible_facts['date_time']['epoch']}}
      always:
        - name: fetch file from url
          ansible.builtin.get_url:
            url: "{{ url }}"
            dest: /home/user

