---
- name: Demonstrate variable usage
  hosts:
    - web
    - database
  tasks:
    - name: Install package {{ package }}
      ansible.builtin.dnf:
        name: "{{ package }}"
        state: present

