---
- name: report generator
  hosts: host0.lab.drv.internal
  tasks:
  - name: evaluate template
    ansible.builtin.template:
      src: templates/report.md.j2
      dest: /var/log/report.md
  - name: get report
    ansible.builtin.fetch:
      src: /var/log/report.md
      dest: reports/{{inventory_hostname}}
      flat: true
