---
- name: Create users with loop using host variables
  hosts:
    - host0.lab.drv.internal
    - host1.lab.drv.internal
  tasks:
    - name: User creation task
      ansible.builtin.user:
        name: "{{ item['name'] }}"
        state: present
        groups: "{{ item['groups'] }}"
      loop: "{{ users }}"
