- name: determine swapsize
  hosts: all
  tasks:
    
    - name: case RAM > 16GB
      ansible.builtin.debug:
        var: ansible_facts['memtotal_mb']
    - name: case RAM > 16GB
      ansible.builtin.debug:
        msg: Swap size must be 16 GB 
      when: (ansible_facts['memtotal_mb'] > 16384)
    - name: case RAM <= 16GB
      ansible.builtin.debug:
        msg: Swap size must be {{ ansible_facts['memtotal_mb']}}
      when: ansible_facts['memtotal_mb'] <= 16384

